// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZTXdqfp7hGaEIn-urHrNC1u6UnORnGQ',
    appId: '1:560188765864:web:0972087acebf9bad2eb49d',
    messagingSenderId: '560188765864',
    projectId: 'nia-mobile-app',
    authDomain: 'nia-mobile-app.firebaseapp.com',
    storageBucket: 'nia-mobile-app.firebasestorage.app',
    measurementId: 'G-616CLB9XZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBMF3FHQjc_QQ9eXBfaYRowoc1dwOGtY0',
    appId: '1:560188765864:android:a985d118f20cd26f2eb49d',
    messagingSenderId: '560188765864',
    projectId: 'nia-mobile-app',
    storageBucket: 'nia-mobile-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy_GaN2uu93k_-Sq02mksB2plC7FFydFs',
    appId: '1:560188765864:ios:407e5a6b6634af112eb49d',
    messagingSenderId: '560188765864',
    projectId: 'nia-mobile-app',
    storageBucket: 'nia-mobile-app.firebasestorage.app',
    iosClientId: '560188765864-3nkjc4gt1n87eneqg3dghn6d5qo34m5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.niaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy_GaN2uu93k_-Sq02mksB2plC7FFydFs',
    appId: '1:560188765864:ios:407e5a6b6634af112eb49d',
    messagingSenderId: '560188765864',
    projectId: 'nia-mobile-app',
    storageBucket: 'nia-mobile-app.firebasestorage.app',
    iosClientId: '560188765864-3nkjc4gt1n87eneqg3dghn6d5qo34m5c.apps.googleusercontent.com',
    iosBundleId: 'com.example.niaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaZTXdqfp7hGaEIn-urHrNC1u6UnORnGQ',
    appId: '1:560188765864:web:a0e7ae47f83c91062eb49d',
    messagingSenderId: '560188765864',
    projectId: 'nia-mobile-app',
    authDomain: 'nia-mobile-app.firebaseapp.com',
    storageBucket: 'nia-mobile-app.firebasestorage.app',
    measurementId: 'G-JS0K0PNYFR',
  );
}
